config/routes.rb
Rails.application.routes.draw do
  get 'produtos/index'
  root 'produtos#index'
  resources :produtos
end

app/models/produto.rb
class Produto < ActiveRecord::Base
  validates_numericality_of :qtd, :only_integer => true
  validates_numericality_of :preco
  validates_presence_of :nome , :preco , :qtd , :tipo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  def index
    @produtos = Produto.all
    @produto = Produto.new
  end

  def show
    @produto = Produto.find(params[:id])
  end

  def new
    @produto = Produto.new
  end

  def edit
    @produto = Produto.find(params[:id])


    redirect_to update
  end

  def create
    @produto = Produto.new(produto_params)
    @produto.preco.to_f
    @produto.qtd.to_i

    if @produto.save
      redirect_to :root
    else
      redirect_to :back
    end
  end

  def update
    @produto = Produto.find(params[:id])
    if @produto.update(produto_params)
      redirect_to :root
    else
      redirect_to :back
    end
  end

  def destroy
    @produto = Produto.find(params[:id])
    @produto.destroy

    redirect_to produtos_path
  end

  private
    def produto_params
      params.require(:produto).permit(:nome,:preco,:qtd,:tipo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mercadoria_helper.rb
module MercadoriaHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PrjValemobi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/produtos/index.html.erb
<!DOCTYPE html>
<html ng-app="Negocia">
  <head>
    <meta charset="utf-8">
    <meta name="viewport"
          content="initial-scale=1, maximum-scale=1, width=device-width"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Bree+Serif" rel="stylesheet">

    <link rel="stylesheet" href="/assets/stylesheets/produtos.css">
    <title>Negocia Já</title>
  </head>

  <body>
      <header>
        <h1>Negocia Já</h1>
        <h2>Uma plataforma para comprar e vender produtos</h2>
      </header>

      <section>
        <ul class="nav nav-tabs">
          <li><a data-toggle="tab" href="#compra">Itens Anunciados</a></li>
          <li class="active"><a data-toggle="tab" href="#venda">Meus Anúncios</a></li>
        </ul>
        <div class="tab-content">
          <div id="compra" class="tab-pane fade">
            <h3>Produtos</h3>
            <div class="table-responsive">
              <table class="table table-striped">
              <tr>
                <th>Código do Produto</th>
                <th>Nome do Produto</th>
                <th>Preço</th>
                <th>Quantidade</th>
                <th>Tipo do Produto</th>
              </tr>

              <% @produtos.each do |produto| %>
                <tr>
                  <td><%= produto.id %></td>
                  <td><%= produto.nome %></td>
                  <td><%= produto.preco %></td>
                  <td><%= produto.qtd %></td>
                  <td><%= produto.tipo%></td>
                </tr>
              <% end %>

            </table>
            </div>
          </div>
          <div id="venda" class="tab-pane fade in active">
            <h3>Produtos</h3>
            <div class="table-responsive">
              <table class="table table-striped">
              <tr>
                <th>Código do Produto</th>
                <th>Nome do Produto</th>
                <th>Preço</th>
                <th>Quantidade</th>
                <th>Tipo do Produto</th>
                <th>Operação</th>
              </tr>

              <% @produtos.each do |produto| %>
                <tr>
                  <td><%= produto.id %></td>
                  <td><%= produto.nome %></td>
                  <td><%= produto.preco %></td>
                  <td><%= produto.qtd %></td>
                  <td><%= produto.tipo%></td>
                  <td>
                    <%= link_to "Editar", produto_path(produto) %>
                    <%= link_to 'Excluir', produto_path(produto.id),
                        method: :delete,
                        data: { confirm: 'Você está certo disso?' }
                        %>
                  </td>
                </tr>
              <% end %>
            </table>
            </div>
            <%= link_to 'Colocar produto a venda', new_produto_path %>

          </div>
        </div>
      </section>

      <footer>
        <h2>Contato</h2>
        <ul>
            <li>
                <a href="tel:15981219298"><span class="fa fa-whatsapp"></span></a>
            </li>
            <li>
                <a href="mailto:vitormd97@gmail.com"><span class="fa fa-envelope"></span></a>
            </li>
            <li>
              <a href = "https://github.com/Vitormdias/prjValemobi" target = "_blank"><span class="fa fa-github-square"></span></a>
            </li>
            <li>
              <a href = "https://linkedin.com/in/vitor-manfré-dias-323a27128" target = "_blank" ><span class="fa fa-linkedin-square"></span></a>
            </li>
        </ul>
      </footer>
  </body>
</html>

app/views/produtos/new.html.erb
<link rel="stylesheet" href="/assets/stylesheets/form.css">
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<h1 id="add">Adicionar</h1>
<%= form_for @produto do |f| %>
    <div class="form">
        <%= f.label :nome %>
        <div class="input">
            <%= f.text_field :nome %>
        </div>
        <%= f.label :preço %>
        <div class="input">
            <%= f.text_field :preco %>
        </div>
        <%= f.label :qtd %>
        <div class="input">
            <%= f.text_field :qtd %>
        </div>
        <%= f.label :tipo %>
        <div class="input">
            <%= f.text_field :tipo %>
        </div>
        <input type="submit" name="commit" value="Adicionar Produto" class="btn btn-primary btn-md">
    </div>
<% end %>

app/views/produtos/show.html.erb
<link rel="stylesheet" href="/assets/stylesheets/form.css">
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<h1 id="edit">Editar</h1>
<%= form_for @produto do |f| %>
    <div class="form">
        <%= f.label :nome %>
        <div class="input">
            <%= f.text_field :nome %>
        </div>
        <%= f.label :preço %>
        <div class="input">
            <%= f.text_field :preco %>
        </div>
        <%= f.label :qtd %>
        <div class="input">
            <%= f.text_field :qtd %>
        </div>
        <%= f.label :tipo %>
        <div class="input">
            <%= f.text_field :tipo %>
        </div>
        <input type="submit" name="commit" value="Atualizar Produto" class="btn btn-primary btn-md">
    </div>
<% end %>